name: MineReset
main: falkirks\minereset\MineReset
version: 3.3.0
author: Falk
translator: WolfTubeTM
api: [3.0.0, 4.0.0]
load: POSTWORLD
softdepend: [SimpleWarp, EasyForms]
permissions:
 minereset:
  default: op
  children:
   minereset.command:
    default: op
    description: Quyền cho phép sử dụng tất cả lệnh MineReset.
    children:
      minereset.command.about:
        description: Quyền cho phép xem thông tin plugin.
      minereset.command.edit:
        description: Quyền cho phép chỉnh sửa.
      minereset.command.report:
        description: Quyền cho phép gửi báo cáo tới Github.
      minereset.command.create:
        description: Quyền cho phép thêm mới khu mine.
      minereset.command.set:
        description: Quyền cho phép set block cho khu mine.
      minereset.command.reset:
        description: Quyền cho phép reset khu mine.
      minereset.command.destroy:
        description: Quyền cho phép xóa khu mine.
      minereset.command.resetall:
        description: Quyền cho phép reset tất cả khu mine.
